# Generated by Django 4.1.6 on 2023-02-10 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isClosed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAvailableSeats', models.IntegerField()),
                ('isOpen', models.BooleanField()),
                ('isCancelled', models.BooleanField()),
                ('isComplete', models.BooleanField()),
                ('tripDateAndTime', models.DateTimeField()),
                ('pickupLocation', models.CharField(max_length=50)),
                ('dropoffLocation', models.CharField(max_length=50)),
                ('vehicle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('numTripsAsDriver', models.IntegerField()),
                ('numTripsAsPassenger', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersInteractedForUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasReviewed', models.BooleanField()),
                ('theInteracter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacts_with', to='rideMeApp.user')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has', to='rideMeApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UsersInteractedForPostings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.posting')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(max_length=2)),
                ('description', models.CharField(max_length=500)),
                ('reviewedUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.user')),
                ('reviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='rideMeApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.user'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('conversationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.conversation')),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='passengerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.user'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='postingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.posting'),
        ),
        migrations.CreateModel(
            name='ApprovedPassengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.posting')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.user')),
            ],
        ),
    ]
