# Generated by Django 4.1.6 on 2023-02-14 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posting',
            name='isCancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posting',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posting',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='averageRating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='numTripsAsDriver',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='numTripsAsPassenger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 56, 22, 255430, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usersinteractedforusers',
            name='hasReviewed',
            field=models.BooleanField(default=False),
        ),
    ]
