# Generated by Django 4.1.6 on 2023-02-15 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0010_alter_conversation_isclosed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='tripDate',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
        migrations.AddField(
            model_name='posting',
            name='tripTime',
            field=models.TimeField(default=datetime.time(10, 30)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 21, 33, 42, 901991, tzinfo=datetime.timezone.utc)),
        ),
    ]
