# Generated by Django 4.1.6 on 2023-02-15 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0011_posting_tripdate_posting_triptime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='tripDateAndTime',
            new_name='tripSubmitted',
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 21, 37, 47, 850006, tzinfo=datetime.timezone.utc)),
        ),
    ]
