# Generated by Django 4.1.6 on 2023-02-16 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0014_message_hasread_alter_user_registrationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='latestMessageSentTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 14, 13, 11, 231837, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='message',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 14, 13, 11, 231837, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 14, 13, 11, 229619, tzinfo=datetime.timezone.utc)),
        ),
    ]
