# Generated by Django 4.1.6 on 2023-02-16 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0015_conversation_latestmessagesenttime_message_timesent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='latestMessageSentTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 19, 54, 6, 210645, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 19, 54, 6, 210645, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 19, 54, 6, 210645, tzinfo=datetime.timezone.utc)),
        ),
    ]
