# Generated by Django 4.1.6 on 2023-02-16 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0016_alter_conversation_latestmessagesenttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hasUnreadMessagesCurUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='latestMessageSentTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 20, 0, 22, 148753, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 20, 0, 22, 148753, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 20, 0, 22, 148753, tzinfo=datetime.timezone.utc)),
        ),
    ]
