# Generated by Django 4.1.6 on 2023-02-16 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0018_alter_conversation_latestmessagesenttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='latestMessageSentTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 23, 47, 56, 17565, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 23, 47, 56, 18574, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 23, 47, 56, 14567, tzinfo=datetime.timezone.utc)),
        ),
    ]
