# Generated by Django 4.1.6 on 2023-02-17 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0019_alter_conversation_latestmessagesenttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedpassengers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='latestMessageSentTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 13, 0, 16, 560458, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 13, 0, 16, 560458, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 13, 0, 16, 557448, tzinfo=datetime.timezone.utc)),
        ),
    ]
