# Generated by Django 4.1.6 on 2023-02-17 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0020_alter_approvedpassengers_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewedUserType',
            field=models.CharField(default='passenger', max_length=20),
        ),
        migrations.AddField(
            model_name='usersinteractedforusers',
            name='InteractionType',
            field=models.CharField(default='passenger', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='latestMessageSentTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 15, 23, 43, 74143, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 15, 23, 43, 75141, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 15, 23, 43, 68144, tzinfo=datetime.timezone.utc)),
        ),
    ]
