# Generated by Django 4.1.6 on 2023-02-17 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0021_review_reviewedusertype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='averageRating',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='latestMessageSentTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 15, 48, 56, 618609, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 15, 48, 56, 618609, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 15, 48, 56, 616615, tzinfo=datetime.timezone.utc)),
        ),
    ]
