# Generated by Django 4.1.6 on 2023-03-09 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0025_posting_tripprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='submissionTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 14, 58, 5, 786190, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='usersinteractedforusers',
            name='postingID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.posting'),
        ),
    ]
