# Generated by Django 4.1.6 on 2023-03-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0026_review_submissiontime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='submissionTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
