# Generated by Django 4.1.6 on 2023-03-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0027_alter_review_submissiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinteractedforusers',
            name='postingID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rideMeApp.posting'),
        ),
    ]
