# Generated by Django 4.1.6 on 2023-04-02 01:58

from django.db import migrations, models
import rideMeApp.models


class Migration(migrations.Migration):
    dependencies = [
        ("rideMeApp", "0030_alter_user_securityquestionanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profilePicture",
            field=models.ImageField(
                blank=True, null=True, upload_to=rideMeApp.models.user_directory_path
            ),
        ),
    ]
