# Generated by Django 4.1.6 on 2023-02-11 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0004_user_email_alter_posting_tripdateandtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='tripDateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 17, 37, 46, 905179, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 17, 37, 46, 905179, tzinfo=datetime.timezone.utc)),
        ),
    ]
