# Generated by Django 4.1.6 on 2023-02-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0006_alter_posting_tripdateandtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='tripDateAndTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(),
        ),
    ]
