# Generated by Django 4.1.6 on 2023-03-03 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideMeApp', '0022_remove_user_averagerating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='latestMessageSentTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 21, 23, 3, 765639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 21, 23, 3, 765639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 21, 23, 3, 765639, tzinfo=datetime.timezone.utc)),
        ),
    ]
